#-------------------------------
# General Site Settings

title: Xin (Julia) Xu
description: Data Scientist / Bayesian / Traveller
email: juliaxu0304@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Blog, url: '#posts'}
- {name: Project, url: '#projects'}  ## change url
- {name: Contact, url: '#contact'}


#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'This is Xin Xu Homepage. I am a new-grad from Duke and a problem solver in Data Science. I record some Tech reviews and post my thoughts about Machine Learning, Statistics, Predictive Modeling here. Welcome to visit and contact with me.'
  rel-author: 'https://sheliaxin.github.io/Xin-Xu-Homepage/'
  rel-publisher: 'https://sheliaxin.github.io/Xin-Xu-Homepage/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  I am a new-grad from Duke and **a problem solver in Data Science**.
  I live in Los Angeles, and specializes in exploring insights from data.
  Related Projects can be found on [my github](https://github.com/SheliaXin){:target="_blank"}.


skills:
- {name: Statistics, value: '9'}
- {name: Python, value: '9'}
- {name: Machine Learning, value: '9'}
- {name: R, value: '9'}
- {name: Predictive Modeling, value: '8'}
- {name: SQL, value: '8'}
- {name: Data Mining, value: '7'}
- {name: Hadoop, value: '6'}

#-------------------------------
# Posts Section


#-------------------------------
# Projects Section

projects:
- {quote: '<p> Since K-means algorithm has a critical problems that it might be blocked
  locally based on the initial random chosen centers, many related algorithn, such as K-means++,
  has been developed to solve this problem. This project reproducted Scalable K-means++ algorithm
  in Bahmani et al. paper, optimized their performance with Cython, multiprocessing, pySpark,
  and compared misclassification rate, clustering cost, and runtime performance on
  four large datasets. <a href="https://github.com/SheliaXin/Scalable-K-means-"> >> More Details </a>
  </p>',
  logo: 'kmeans.png'}

- {quote: '<p>In this project, we use <strong> Gaussian Hidden Markov Model</strong>
  to catch the stock price pattern and forecast the stock price of seven high-tech companies,
  and compared it to traditional time series models. Instead of assuming independent
  observation, we consider Hidden Markov Model with correlated observations,
  by adding closing price difference. The four latent statuses in our HMM models can
  basically catch the increasing and decreasing pattern, and under some simple
  investment strategy, HMM model has a more stable and better pay-offs than
  traditional time series models.</p>',
  logo: 'stock.png'}

- {quote: '<p><strong>.</p>',
  logo: 'reddit.png'}

- {quote: '<p><strong>.D</p>',
  logo: 'H1B.png'}
#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/xin-julia-xu'}
- {icon: 'github', link: 'https://github.com/SheliaXin'}
- {icon: 'facebook', link: 'https://www.facebook.com/xin.xu.9674'}
- {icon: 'twitter', link: 'https://twitter.com/CodingJulia'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
